name: Auto Approve

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
        if: github.actor == 'nareshipme'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
